version: '3.8'

services:
  web:
    image: 654654437668.dkr.ecr.us-east-1.amazonaws.com/flask-mysql:latest
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw